# number of retries
attempts: 1

# use accounts in random order - true / false
shuffle_accounts: false

# RPCs, change if you want
ETH_RPC: "https://eth.llamarpc.com"

# Bot will wait until ethereum gas is lower than number below
MAX_GAS: 25

# mobile proxy (yes or no)
mobile_proxy: "no"
change_ip_pause: 20
